# --- Database connection ---
url=jdbc:postgresql://db:5432/myusers
username=postgres
password=mk2908002
driver=org.postgresql.Driver

# --- Changelog configuration ---
changeLogFile=changelog/db.changelog-master.xml

# --- Optional (for cleaner output) ---
logLevel=info
liquibase.hub.mode=off
